-   id: check-line-endings
    name: Check line endings
    description: Check line endings stored in repo
    entry: check_line_endings
    language: python
    types: [text]
-   id: check-trailing-whitespaces
    name: Check trailing whitespaces
    description: Check trailing whitespaces
    entry: check_trailing_whitespaces
    language: python
    types: [text]
-   id: check-end-of-file
    name: Check end of files
    description: Check that file is empty or ends with one line break
    entry: check_end_of_file
    language: python
    types: [text]
-   id: check-q_emit-macro
    name: Check Q_EMIT macro usages
    description: Check that Q_EMIT macro is not used as callable
    entry: check_q_emit
    language: python
    types: [text]
